@baseUrl = http://localhost:8000/api
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2xvZ2luIiwiaWF0IjoxNzcwOTU4NzYzLCJleHAiOjE3NzA5NjIzNjMsIm5iZiI6MTc3MDk1ODc2MywianRpIjoiOWJzNG13QTFRSnhZV093RCIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.wu_QwH6TFn2AegpGBpKwGx1mzdz6YzmBeZPmrxn4_xI
POST {{baseUrl}}/login
Content-Type: application/json
Accept: application/json

{
  "email": "bendahara@example.com",
  "password": "password123"
}

### CREATE PEMASUKAN
POST {{baseUrl}}/pemasukan
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "kode_transaksi": "PM-001",
  "nama_transaksi": "Dana Punia Bulanan",
  "kategori_id": 2,
  "qty": 10,
  "harga_satuan": 50000,
  "sumber_dana": "Umat Banjar",
  "deskripsi": "Punia rutin bulan Februari"
}


### GET ALL PEMASUKAN
GET {{baseUrl}}/pemasukan
Authorization: Bearer {{token}}
Accept: application/json


### GET PEMASUKAN BY ID
GET {{baseUrl}}/pemasukan/1
Authorization: Bearer {{token}}
Accept: application/json

### UPDATE PEMASUKAN
PUT {{baseUrl}}/pemasukan/1
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "nama_transaksi": "Dana Punia Bulanan Update",
  "qty": 12,
  "harga_satuan": 50000,
  "deskripsi": "Update jumlah punia"
}


### DELETE PEMASUKAN
DELETE {{baseUrl}}/pemasukan/1
Authorization: Bearer {{token}}
Accept: application/json


